// <auto-generated />
using System;
using DEMO_ASP.NET_CORE_MVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DEMO_ASP.NET_CORE_MVC.Migrations
{
    [DbContext(typeof(RestaurantContext))]
    [Migration("20181019115742_RecipeSeedData")]
    partial class RecipeSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DEMO_ASP.NET_CORE_MVC.Models.Recipe", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Quantity");

                    b.Property<string>("RecipeName");

                    b.Property<DateTime>("RegisterDate");

                    b.Property<bool>("isAvailable");

                    b.HasKey("ID");

                    b.ToTable("Recipe");

                    b.HasData(
                        new { ID = 1, Quantity = 41, RecipeName = "French fries", RegisterDate = new DateTime(2018, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), isAvailable = true },
                        new { ID = 2, Quantity = 31, RecipeName = "Spaghetti", RegisterDate = new DateTime(2016, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), isAvailable = true },
                        new { ID = 3, Quantity = 0, RecipeName = "Pizza", RegisterDate = new DateTime(2017, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), isAvailable = false },
                        new { ID = 4, Quantity = 50, RecipeName = "Curry", RegisterDate = new DateTime(2012, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), isAvailable = true },
                        new { ID = 5, Quantity = 60, RecipeName = "Baguette", RegisterDate = new DateTime(2013, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), isAvailable = true },
                        new { ID = 6, Quantity = 57, RecipeName = "Mashed potato", RegisterDate = new DateTime(2015, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), isAvailable = true },
                        new { ID = 7, Quantity = 0, RecipeName = "Lasagna", RegisterDate = new DateTime(2011, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), isAvailable = false },
                        new { ID = 8, Quantity = 88, RecipeName = "Ravioli", RegisterDate = new DateTime(2018, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), isAvailable = true }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
